os: osx
language: objective-c
sudo: false
osx_image: xcode10.1
matrix:
  include:
    - name: "OversimplifiedDemo / iPhone 7 / iOS 11.4 / Xcode 10.0 / macOS 10.13"
      osx_image: "xcode10"
      env: MIXBOX_CI_DESTINATION="iphone_7_ios114.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/demo_tests" MIXBOX_CI_REPORTS_PATH="."
    - name: "OversimplifiedDemo / iPhone 7 / iOS 11.4 / Xcode 10.1 / macOS 10.13"
      osx_image: "xcode10.1"
      env: MIXBOX_CI_DESTINATION="iphone_7_ios114.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/demo_tests" MIXBOX_CI_REPORTS_PATH="."
    - name: "OversimplifiedDemo / iPhone X / iOS 12.1 / Xcode 10.2.1 / macOS 10.14"
      osx_image: "xcode10.2"
      env: MIXBOX_CI_DESTINATION="iphone_x_ios121.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/demo_tests" MIXBOX_CI_REPORTS_PATH="."
    - name: "Logic Tests / iPhone 6 / iOS 9.3 / Xcode 10.0 / macOS 10.13"
      osx_image: "xcode10"
      env: MIXBOX_CI_DESTINATION="iphone_6_plus_ios93.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/logic_tests" MIXBOX_CI_REPORTS_PATH="."
    - name: "Logic Tests / iPhone 7 / iOS 11.4 / Xcode 10.1 / macOS 10.13"
      osx_image: "xcode10.1"
      env: MIXBOX_CI_DESTINATION="iphone_7_ios114.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/logic_tests" MIXBOX_CI_REPORTS_PATH="."
    - name: "Logic Tests / iPhone X / iOS 12.1 / Xcode 10.2.1 / macOS 10.14"
      osx_image: "xcode10.2"
      env: MIXBOX_CI_DESTINATION="iphone_x_ios121.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/logic_tests" MIXBOX_CI_REPORTS_PATH="."
    - name: "IPC Demo / Xcode 10.2.1 / macOS 10.14"
      osx_image: "xcode10.2"
      env: MIXBOX_CI_DESTINATION="iphone_7_ios114.json" MIXBOX_CI_TRAVIS_BUILD="ci/builds/ipc_demo_tests" MIXBOX_CI_REPORTS_PATH="."
script:
    ci/travis/run_build_with_travis